apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: my-namespace
spec:
  encryptedData:
    password: AgAuIf//tMIi5s1LTB3TEeFlpdUho9Da4x1uMKSdsvn9Vbo8F39yfUQifikgHEK4eHKTmAkQnT8zQaU6AU9hxL2PHy5a5ygcaKeW8V5vZ6kTkwXzjvxZOg/PiFE04X+CS9uVnPLz3ngzghac/ThTOay7h/bwySx5ZhBF8f7Ic/07xuMCC+jBt2Xz1pyTnXD5mwZjRpkiPp6SXsZKCiRXcH7wFlxrXAJ9zNG0LZusG39n14KS3QdQX8TvOEWjIlU+mgEodWBvZCD3sXy5CqAGwGLQn/YEOo50aT0cpESaiDS8uEvwQQ1eUBSSErWifdWEniaQhICJqONYK40f7slzebCKvKNa0MUq9CiJfShmnM4E7y26XGFjy6UnsUwLMSwOfSaYK3iRFRlK0VDw5XSiOv8wh5UaYlQ0pkWA7nZZNYFyGBBSd/otXzmzp0RN4g93T6rS1kld9W1Un61oi985L7kQq4fTTHn4erFJZ1kzDfy0MO8dldzHJznh5mYC4H/TVCLE/qUiMdZ5IwNjLA1cctygU1IdgD6pxGd4PKNUQ1yzTN6ndcfIqlAslPmBI8r91/5eAPIYO5MLAKHT4eUyUMPiOBaot059yWrSglCCi3w31V8fm2xZXlCdRZbO5GMkXJl6cUMwFsehohD0/MWFDy+vbZ4OlFzliZRZ7TEbARRRZsM5yoPyLBXVLd7P3GwQCASgZ5l8pQ==
    username: AgCLKMf1CzZ++MhLUf/9Yh2oMXtn66LnZmVH5b2BRr2L8eYFDU2kmbHFtCo5mKMMKp/dE/aHmIix5jg7zf/65kkZQ/rcKJIHf5vizkJBAZb4jpWgnnRbxhe7ALs3gqZvpeC6CXwVKg5UdgoY6ym77vD21sDvLLvtEUMT9JTpnhqFxFmzicbgRqV99rCXLaZi8Ohrrd9Z8c5SKiMAhbFl8NxeXd0wtOf0ksG+Ya4cR9EKhs0V1bIkEnamJQ1m8bU+G8oq++D+ZT1v4jIBk8OsilG+rEny129Lio/amNn8WDteOEC/S5nLdvUA7OetMcX1Xo81pFqd0JuntU5FvKmABI9+Mp+oOhyySIXZ+UU0MiRnANcZcWuxGEGM18iZV7pMwI/ib+qUjDIrzp5XQ5PcPYcZJNYbfvgRbbz4CgnG/M+IHhhl0pdqKWlA0599Wpg85/xc0pH3Qe8nEWfC2KO97HCx5Q7iVoP+yX8sy9jWKKdOZCt3A5Vb0ckp0TjlKX8Ofyflw08g/LYdl15mxNplGaBK5hf9kZl5Eq/8enDGP4J1jAvh+h3i7cG9wfuXGPFT9teGc1sxLfgmfQVsbOFM91hX2bFkZB1nhfKksxa++bvpg4GddwkZS5mIQt+547SzjmqRAC/UsTUoofjuVm0NXmFOmYf2GyrXJavO0/nUZBKZl3KCi0QH3vGMzFyYYxd+YpaWOOGEjdntRuo=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: my-namespace

